const API='/api';
function getToken(){return localStorage.getItem('exalyte_token')}
function getUser(){return JSON.parse(localStorage.getItem('exalyte_user')||'null')}
function logout(){localStorage.clear();window.location.href='/'}
// Student Mode: lets an admin browse the live student experience (dashboard, exams,
// history, results) using their own admin account. Admin accounts already bypass every
// premium/closed/scheduled restriction server-side, so this is purely a navigation flag —
// it just stops the student pages from bouncing an admin back here, and shows a bar with
// a one-tap way back. Nothing about the admin's actual permissions changes.
function enterStudentMode(){localStorage.setItem('exalyte_student_mode','1');window.location.href='dashboard.html'}
function esc(s){return(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}
function formatDate(iso){return iso?new Date(iso).toLocaleDateString():'—'}
function isImageURL(s){if(!s)return false;const t=s.trim();return t.startsWith('http')&&(t.includes('.jpg')||t.includes('.jpeg')||t.includes('.png')||t.includes('.webp')||t.includes('.gif')||t.includes('ibb.co')||t.includes('images.unsplash.com')||t.includes('i.imgur.com'))}
function formatTimeTaken(s){if(!s||s<=0)return'N/A';const m=Math.floor(s/60),sec=Math.floor(s%60);return m>0?m+'m '+sec+'s':sec+'s'}
async function apiFetch(path,opts={}){const t=getToken();const h={'Content-Type':'application/json',...(t?{Authorization:'Bearer '+t}:{})};try{const r=await fetch(API+path,{...opts,headers:h});return{ok:r.ok,status:r.status,data:await r.json().catch(()=>({}))}}catch(networkErr){return{ok:false,status:0,data:{error:'Network error: '+(networkErr.message||networkErr)}}}}
function toast(m){const t=document.getElementById('toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3000)}

let allExams=[],allBatches=[],allUsers=[],editingExamId=null,editingBatchId=null,grantUserId=null;
let currentResourceType='exam',currentResourceTargetId=null;
let requiredSections=[],compulsorySections=[],normalSections=[];
const PAGE_SIZE=15;
let usersPageNum=1,examsPageNum=1,batchesPageNum=1,resultsPageNum=1,notifPageNum=1;
function paginateList(list,page,perPage){const totalPages=Math.max(1,Math.ceil(list.length/perPage));const p=Math.min(Math.max(1,page),totalPages);return{items:list.slice((p-1)*perPage,p*perPage),page:p,totalPages,total:list.length}}
function pagerHtml(page,totalPages,total,fn){if(totalPages<=1)return'';let start=Math.max(1,page-2),end=Math.min(totalPages,start+4);start=Math.max(1,end-4);let pages=[];for(let i=start;i<=end;i++)pages.push(i);let html='<div class="pager">';html+=`<button class="pager-btn" ${page<=1?'disabled':''} onclick="${fn}(${page-1})">Prev</button>`;if(start>1){html+=`<button class="pager-btn" onclick="${fn}(1)">1</button>`;if(start>2)html+='<span class="pager-ellipsis">\u2026</span>'}pages.forEach(i=>{html+=`<button class="pager-btn${i===page?' active':''}" onclick="${fn}(${i})">${i}</button>`});if(end<totalPages){if(end<totalPages-1)html+='<span class="pager-ellipsis">\u2026</span>';html+=`<button class="pager-btn" onclick="${fn}(${totalPages})">${totalPages}</button>`}html+=`<button class="pager-btn" ${page>=totalPages?'disabled':''} onclick="${fn}(${page+1})">Next</button>`;html+='</div>';html+=`<div class="pager-info">Page ${page} of ${totalPages} \u00b7 ${total} total</div>`;return html}

function levenshtein(a,b){const m=a.length,n=b.length;if(m===0)return n;if(n===0)return m;const dp=new Array(n+1);for(let j=0;j<=n;j++)dp[j]=j;for(let i=1;i<=m;i++){let prev=dp[0];dp[0]=i;for(let j=1;j<=n;j++){const tmp=dp[j];dp[j]=a[i-1]===b[j-1]?prev:1+Math.min(prev,dp[j],dp[j-1]);prev=tmp}}return dp[n]}
function normalizeSearch(s){return(s||'').toLowerCase().trim().replace(/\s+/g,' ')}
function fieldMatchScore(query,field){if(!field)return -1;const q=normalizeSearch(query),f=normalizeSearch(field);if(!q)return -1;if(f.startsWith(q))return 100;if(f.includes(q))return 90-Math.min(20,f.length-q.length);let best=Infinity;const qLen=q.length;for(let i=0;i<=Math.max(0,f.length-1);i++){const win=f.substr(i,qLen);if(!win)continue;const d=levenshtein(q,win);if(d<best)best=d}best=Math.min(best,levenshtein(q,f));const threshold=qLen<=3?1:Math.ceil(qLen*0.34);if(best<=threshold)return 60-best*8;return -1}
function fuzzyUserSearch(query){const q=normalizeSearch(query);if(!q)return[];return allUsers.map(u=>{const ns=fieldMatchScore(q,u.name);const es=fieldMatchScore(q,u.email);return{...u,_score:Math.max(ns,es)}}).filter(u=>u._score>=0).sort((a,b)=>b._score-a._score).slice(0,15)}

/* ============================================================
   FIXED: searchable-select widget
   Root cause of "select once, then stuck until refresh" AND
   "new exam doesn't appear in list without refresh":
   updateSearchableSelectUI() used to look up the trigger's
   label span via `.querySelector('.placeholder')`, but the very
   same function REMOVES the 'placeholder' class from that span
   once something is selected. So the 2nd call onwards couldn't
   find the span, `trig` was null, and `trig.textContent = ...`
   threw — silently killing whatever function called it
   (including loadExams(), which calls rebuildSearchableSelects()
   BEFORE renderExams(), so the table never re-rendered either).
   Fix: give the span a permanent lookup class `.ss-label`,
   independent of the `.placeholder` style/state class.
   Also: preserve the current selection across rebuilds (e.g.
   after creating/editing an exam) instead of silently resetting
   it to blank every time loadExams()/loadBatches() runs.
   ============================================================ */
const searchableSelects={};
function registerSearchableSelect(wrapId,items,targetInputId,onChange,options={}){
  const prev=searchableSelects[wrapId];
  const preserved=prev?prev.selectedValue:'';
  const defaultValue=options.defaultValue!==undefined?options.defaultValue:preserved;
  searchableSelects[wrapId]={items,selectedValue:defaultValue||'',targetInputId,onChange:onChange||(()=>{}),placeholder:options.placeholder||'Select...'}
}
function updateSearchableSelectUI(wrapId,q){
  const ss=searchableSelects[wrapId];
  if(!ss)return;
  const wrapEl=document.getElementById(wrapId);
  if(!wrapEl)return;
  const list=wrapEl.querySelector('.searchable-select-list');
  const trig=wrapEl.querySelector('.ss-label');
  if(!list||!trig)return;
  let filtered=ss.items;
  if(q){filtered=ss.items.map(i=>({...i,_s:Math.max(fieldMatchScore(q,i.label),fieldMatchScore(q,i.desc||''))})).filter(i=>i._s>=0).sort((a,b)=>b._s-a._s)}
  if(ss.selectedValue){
    const sel=ss.items.find(i=>String(i.value)===String(ss.selectedValue));
    if(sel){trig.textContent=sel.label;trig.classList.remove('placeholder')}
    else{trig.textContent=ss.placeholder;trig.classList.add('placeholder')}
  }else{
    trig.textContent=ss.placeholder;
    trig.classList.add('placeholder')
  }
  list.innerHTML=filtered.length?filtered.map(i=>`<div class="searchable-select-option${String(i.value)===String(ss.selectedValue)?' selected':''}" onclick="selectSearchableOption('${wrapId}','${i.value}')"><span>${esc(i.label)}</span>${i.desc?`<span class="opt-desc">${esc(i.desc)}</span>`:''}</div>`).join(''):'<div class="searchable-select-empty">No matches</div>'
}
function toggleSearchableSelect(id){const w=document.getElementById(id);const open=w.classList.contains('open');document.querySelectorAll('.searchable-select.open').forEach(e=>{if(e.id!==id)e.classList.remove('open')});if(open)w.classList.remove('open');else{w.classList.add('open');updateSearchableSelectUI(id);const inp=w.querySelector('.searchable-select-search input');if(inp){inp.value='';setTimeout(()=>inp.focus(),50)}}}
function filterSearchableOptions(inp){const w=inp.closest('.searchable-select');if(w)updateSearchableSelectUI(w.id,inp.value)}
function selectSearchableOption(id,val){const ss=searchableSelects[id];if(!ss)return;ss.selectedValue=val;const ti=document.getElementById(ss.targetInputId);if(ti){ti.value=val;ti.dispatchEvent(new Event('change',{bubbles:true}))}document.getElementById(id).classList.remove('open');updateSearchableSelectUI(id);if(ss.onChange)ss.onChange(val)}
document.addEventListener('click',e=>{if(!e.target.closest('.searchable-select'))document.querySelectorAll('.searchable-select.open').forEach(el=>el.classList.remove('open'))});

function toggleSectionBuilder(){document.getElementById('sectionBuilder').style.display=document.getElementById('examHasSections').checked?'block':'none'}
function addRequiredSection(d){requiredSections.push({id:Date.now()+Math.random(),name:d?.name||'',count:d?.count||5});renderSections()}
function addCompulsorySection(d){compulsorySections.push({id:Date.now()+Math.random(),name:d?.name||'',count:d?.count||5});renderSections()}
function addNormalSection(d){normalSections.push({id:Date.now()+Math.random(),name:d?.name||'',count:d?.count||5});renderSections()}
function removeSection(list,id){if(list==='req')requiredSections=requiredSections.filter(s=>s.id!==id);if(list==='comp')compulsorySections=compulsorySections.filter(s=>s.id!==id);if(list==='norm')normalSections=normalSections.filter(s=>s.id!==id);renderSections()}
function updateSectionField(list,id,field,val){const arr=list==='req'?requiredSections:list==='comp'?compulsorySections:normalSections;const s=arr.find(x=>x.id===id);if(s){if(field==='name')s.name=val;if(field==='count')s.count=parseInt(val)||0}}
function renderSections(){const rs=document.getElementById('requiredSectionsList'),cs=document.getElementById('compulsorySectionsList'),ns=document.getElementById('normalSectionsList');rs.innerHTML=requiredSections.length?requiredSections.map(s=>`<div class="section-row"><input type="text" placeholder="Section name" value="${esc(s.name)}" onchange="updateSectionField('req',${s.id},'name',this.value)"><input type="number" placeholder="MCQ" value="${s.count}" onchange="updateSectionField('req',${s.id},'count',this.value)"><button class="btn-remove" onclick="removeSection('req',${s.id})">✕</button></div>`).join(''):'<p style="color:var(--t4);font-size:.75rem;padding:8px">None</p>';cs.innerHTML=compulsorySections.length?compulsorySections.map(s=>`<div class="section-row"><input type="text" placeholder="Section name" value="${esc(s.name)}" onchange="updateSectionField('comp',${s.id},'name',this.value)"><input type="number" placeholder="MCQ" value="${s.count}" onchange="updateSectionField('comp',${s.id},'count',this.value)"><button class="btn-remove" onclick="removeSection('comp',${s.id})">✕</button></div>`).join(''):'<p style="color:var(--t4);font-size:.75rem;padding:8px">None</p>';ns.innerHTML=normalSections.length?normalSections.map(s=>`<div class="section-row"><input type="text" placeholder="Section name" value="${esc(s.name)}" onchange="updateSectionField('norm',${s.id},'name',this.value)"><input type="number" placeholder="MCQ" value="${s.count}" onchange="updateSectionField('norm',${s.id},'count',this.value)"><button class="btn-remove" onclick="removeSection('norm',${s.id})">✕</button></div>`).join(''):'<p style="color:var(--t4);font-size:.75rem;padding:8px">None</p>'}

function clearQuestionsJson(){const t=document.getElementById('questionsJson');if(t)t.value='';const r=document.getElementById('questionUploadResult');if(r)r.innerHTML=''}
document.getElementById('uploadSectionSelect').addEventListener('change',clearQuestionsJson);

function updateUploadSectionSelector(examId){const wrap=document.getElementById('uploadSectionWrap');const sel=document.getElementById('uploadSectionSelect');if(!wrap||!sel)return;const exam=allExams.find(e=>e.id==examId);if(exam?.has_sections&&exam?.section_config){try{const c=JSON.parse(exam.section_config);const all=[...(c.required||[]).map(s=>s.name),...(c.compulsory_group||[]).map(s=>s.name),...(c.normal_group||[]).map(s=>s.name)];sel.innerHTML='<option value="">All Sections</option>'+all.map(s=>`<option value="${esc(s)}">${esc(s)}</option>`).join('');wrap.classList.add('show')}catch(e){wrap.classList.remove('show')}}else{wrap.classList.remove('show')}}

function rebuildSearchableSelects(){registerSearchableSelect('questionExamSelectWrap',allExams.map(e=>({value:e.id,label:e.name,desc:e.batch_name||''})),'questionExamSelect',(val)=>{if(val){clearQuestionsJson();loadQuestionsForExam();updateUploadSectionSelector(val)}});registerSearchableSelect('resourceExamSelectWrap',allExams.map(e=>({value:e.id,label:e.name,desc:e.batch_name||''})),'resourceExamSelect',(val)=>{if(val)loadResourcesForTarget()});registerSearchableSelect('resourceBatchSelectWrap',allBatches.map(b=>({value:b.id,label:b.name,desc:(b.exam_count||0)+' exams'})),'resourceBatchSelect',(val)=>{if(val)loadResourcesForTarget()});registerSearchableSelect('resultFilterExamWrap',[{value:'',label:'All Exams',desc:''},...allExams.map(e=>({value:e.id,label:e.name,desc:e.batch_name||''}))],'resultFilterExam',(val)=>{resultsPageNum=1;loadResults()});registerSearchableSelect('examBatchSelectWrap',[{value:'',label:'No batch',desc:''},...allBatches.map(b=>({value:b.id,label:b.name,desc:(b.exam_count||0)+' exams'}))],'examBatchSelect',()=>{},{placeholder:'Select batch (optional)'});registerSearchableSelect('batchCodesSelectWrap',allBatches.map(b=>({value:b.id,label:b.name,desc:(b.exam_count||0)+' exams'})),'batchCodesSelect',(val)=>{if(val){document.getElementById('batchCodesPanel').style.display='block';document.getElementById('newCodeBanner').innerHTML='';loadBatchCodes()}else{document.getElementById('batchCodesPanel').style.display='none'}});Object.keys(searchableSelects).forEach(k=>updateSearchableSelectUI(k))}

async function loadDashboard(){const user=getUser();if(!user?.is_admin){window.location.href='/';return}const[exams,batches,users,results]=await Promise.all([apiFetch('/exams'),apiFetch('/batches'),apiFetch('/admin/users'),apiFetch('/admin/results')]);
  const failures=[];
  if(!exams.ok)failures.push('/exams -> '+exams.status+' '+(exams.data.error||JSON.stringify(exams.data)));
  if(!batches.ok)failures.push('/batches -> '+batches.status+' '+(batches.data.error||JSON.stringify(batches.data)));
  if(!users.ok)failures.push('/admin/users -> '+users.status+' '+(users.data.error||JSON.stringify(users.data)));
  if(!results.ok)failures.push('/admin/results -> '+results.status+' '+(results.data.error||JSON.stringify(results.data)));
  const banner=document.getElementById('debugErrorBanner');
  if(banner){if(failures.length){banner.style.display='block';banner.innerHTML='<strong>Data failed to load. Details:</strong><br>'+failures.map(f=>esc(f)).join('<br>')}else{banner.style.display='none'}}
  const el=Array.isArray(exams.data?.exams)?exams.data.exams:[],bl=Array.isArray(batches.data)?batches.data:[],ul=Array.isArray(users.data)?users.data:[],rl=Array.isArray(results.data)?results.data:[];document.getElementById('statExams').textContent=el.length;document.getElementById('statBatches').textContent=bl.length;document.getElementById('statUsers').textContent=ul.length;document.getElementById('statSubmissions').textContent=rl.length;document.getElementById('recentTable').innerHTML=`<table><thead><tr><th>Rank</th><th>User</th><th>Exam</th><th>Score</th><th>%</th><th>Date</th></tr></thead><tbody>${rl.slice(0,10).map(r=>`<tr><td>#${r.rank||'—'}</td><td><strong>${esc(r.user_name)}</strong><br><span style="font-size:.65rem;color:var(--t4)">${esc(r.email)}</span></td><td>${esc(r.exam_name)}</td><td>${r.score}/${r.total_questions}</td><td>${(r.percentage||0).toFixed(1)}%</td><td>${formatDate(r.submitted_at)}</td></tr>`).join('')||'<tr><td colspan="6">No submissions</td></tr>'}</tbody></table>`}
async function loadExams(){const{data}=await apiFetch('/exams');allExams=Array.isArray(data?.exams)?data.exams:[];rebuildSearchableSelects();renderExams()}
async function loadBatches(){const{data}=await apiFetch('/batches');allBatches=Array.isArray(data)?data:[];rebuildSearchableSelects();renderBatches()}

function renderExams(){const q=normalizeSearch(document.getElementById('examSearchInput').value||'');let filteredAll=allExams;if(q){filteredAll=allExams.map(e=>({...e,_s:Math.max(fieldMatchScore(q,e.name),fieldMatchScore(q,e.description||''),fieldMatchScore(q,e.batch_name||''))})).filter(e=>e._s>=0).sort((a,b)=>b._s-a._s)}const{items:filtered,page,totalPages,total}=paginateList(filteredAll,examsPageNum,PAGE_SIZE);examsPageNum=page;document.getElementById('examsTable').innerHTML=`<table><thead><tr><th>Name</th><th>Batch</th><th>Type</th><th>Status</th><th>Marks/Q</th><th>Questions</th><th>Leaderboard</th><th>Actions</th></tr></thead><tbody>${filtered.map(e=>{let st='<span class="badge badge-open">Open</span>';if(e.is_closed)st='<span class="badge badge-closed">Closed</span>';else if(e.is_live)st='<span class="badge badge-live">Live</span>';else if(e.scheduled_at&&new Date(e.scheduled_at)>new Date())st='<span class="badge badge-scheduled">Scheduled</span>';return `<tr><td><strong>${esc(e.name)}</strong>${e.has_sections?' <span class="badge badge-sectional">Sectional</span>':''}${e.is_practice_exam?' <span class="badge badge-sectional" style="background:#e0e7ff;color:#4338ca">Practice-only</span>':''}${e.description?`<br><span style="font-size:.65rem;color:var(--t4)">${esc(e.description)}</span>`:''}</td><td>${esc(e.batch_name)||'—'}</td><td><span class="badge ${e.is_premium?'badge-premium':'badge-free'}">${e.is_premium?'Premium':'Free'}</span></td><td>${st}</td><td>${e.marks_per_question||1}</td><td>${e.question_count||0}</td><td>${e.leaderboard_enabled?'<span class="badge badge-open">On</span>':'<span class="badge badge-closed">Off</span>'}</td><td><button class="btn btn-outline btn-sm" onclick="openExamModal(${e.id})">Edit</button><button class="btn btn-outline btn-sm" style="color:${e.is_closed?'var(--green)':'var(--red)'}" onclick="toggleExam(${e.id})">${e.is_closed?'Open':'Close'}</button><button class="btn btn-danger btn-sm" onclick="deleteExam(${e.id})">Delete</button></td></tr>`}).join('')||'<tr><td colspan="8" style="text-align:center;padding:24px;color:var(--t3)">No exams found</td></tr>'}</tbody></table>${pagerHtml(page,totalPages,total,'goToExamsPage')}`}
function goToExamsPage(p){examsPageNum=p;renderExams()}
function renderBatches(){const q=normalizeSearch(document.getElementById('batchSearchInput').value||'');let filteredAll=allBatches;if(q){filteredAll=allBatches.map(b=>({...b,_s:Math.max(fieldMatchScore(q,b.name),fieldMatchScore(q,b.description||''))})).filter(b=>b._s>=0).sort((a,b)=>b._s-a._s)}const{items:filtered,page,totalPages,total}=paginateList(filteredAll,batchesPageNum,PAGE_SIZE);batchesPageNum=page;document.getElementById('batchesTable').innerHTML=`<table><thead><tr><th>Name</th><th>Fee</th><th>Exams</th><th>Visibility</th><th>Actions</th></tr></thead><tbody>${filtered.map(b=>`<tr><td><strong>${esc(b.name)}</strong></td><td>${b.fee?('৳'+b.fee):'Free'}</td><td><span class="badge badge-free">${b.exam_count||0} exams</span></td><td>${b.is_public?'<span class="badge badge-open">Public</span>':'<span class="badge badge-closed">Hidden</span>'}</td><td><button class="btn btn-outline btn-sm" onclick="openBatchUsersModal(${b.id},'${esc(b.name).replace(/'/g,"\\'")}')">Users</button><button class="btn btn-outline btn-sm" onclick="openBatchModal(${b.id})">Edit</button><button class="btn btn-danger btn-sm" onclick="deleteBatch(${b.id})">Delete</button></td></tr>`).join('')||'<tr><td colspan="5" style="text-align:center;padding:24px;color:var(--t3)">No batches found</td></tr>'}</tbody></table>${pagerHtml(page,totalPages,total,'goToBatchesPage')}`}
function goToBatchesPage(p){batchesPageNum=p;renderBatches()}
function onExamSearchInput(){examsPageNum=1;renderExams()}
function onBatchSearchInput(){batchesPageNum=1;renderBatches()}

function openExamModal(id=null){editingExamId=id;const e=id?allExams.find(x=>x.id==id):null;document.getElementById('examModalTitle').textContent=e?'Edit Exam':'New Exam';document.getElementById('examName').value=e?.name||'';document.getElementById('examDesc').value=e?.description||'';document.getElementById('examTime').value=e?.time_limit||30;document.getElementById('examNeg').value=e?.negative_marking||0;document.getElementById('examMarksPerQ').value=e?.marks_per_question||1;document.getElementById('examLive').value=e?.live_deadline_hours||0;if(e?.scheduled_at){const d=new Date(e.scheduled_at);const local=new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);document.getElementById('examScheduledAt').value=local}else{document.getElementById('examScheduledAt').value=''}document.getElementById('examPremium').checked=e?.is_premium||false;document.getElementById('examPractice').checked=id?!!e?.allow_practice:true;document.getElementById('examLeaderboard').checked=id?!!e?.leaderboard_enabled:true;document.getElementById('examPracticeOnly').checked=e?.is_practice_exam===1;document.getElementById('examHasSections').checked=e?.has_sections===1;document.getElementById('examBatchSelect').value=e?.batch_id||'';if(searchableSelects['examBatchSelectWrap']){searchableSelects['examBatchSelectWrap'].selectedValue=e?.batch_id||'';updateSearchableSelectUI('examBatchSelectWrap')}requiredSections=[];compulsorySections=[];normalSections=[];if(e?.has_sections&&e?.section_config){try{const c=JSON.parse(e.section_config);(c.required||[]).forEach(s=>requiredSections.push({id:Date.now()+Math.random(),name:s.name,count:s.count}));(c.compulsory_group||[]).forEach(s=>compulsorySections.push({id:Date.now()+Math.random(),name:s.name,count:s.count}));(c.normal_group||[]).forEach(s=>normalSections.push({id:Date.now()+Math.random(),name:s.name,count:s.count}));document.getElementById('maxOptional').value=c.max_optional||2;document.getElementById('minCompulsory').value=c.min_from_compulsory||1}catch(e){}}toggleSectionBuilder();renderSections();document.getElementById('examModal').classList.add('open')}
async function saveExam(){const hasSections=document.getElementById('examHasSections').checked;let config='';if(hasSections){config=JSON.stringify({required:requiredSections.filter(s=>s.name.trim()).map(s=>({name:s.name.trim(),count:s.count})),compulsory_group:compulsorySections.filter(s=>s.name.trim()).map(s=>({name:s.name.trim(),count:s.count})),normal_group:normalSections.filter(s=>s.name.trim()).map(s=>({name:s.name.trim(),count:s.count})),max_optional:parseInt(document.getElementById('maxOptional').value)||2,min_from_compulsory:parseInt(document.getElementById('minCompulsory').value)||1})}const sv=document.getElementById('examScheduledAt').value;const body={name:document.getElementById('examName').value.trim(),description:document.getElementById('examDesc').value,time_limit:parseInt(document.getElementById('examTime').value)||30,negative_marking:parseFloat(document.getElementById('examNeg').value)||0,marks_per_question:parseFloat(document.getElementById('examMarksPerQ').value)||1,is_premium:document.getElementById('examPremium').checked?1:0,allow_practice:document.getElementById('examPractice').checked?1:0,leaderboard_enabled:document.getElementById('examLeaderboard').checked?1:0,is_practice_exam:document.getElementById('examPracticeOnly').checked?1:0,batch_id:document.getElementById('examBatchSelect').value||null,live_deadline_hours:parseInt(document.getElementById('examLive').value)||0,scheduled_at:sv?new Date(sv).toISOString():null,has_sections:hasSections?1:0,section_config:config};const url=editingExamId?`/admin/exams/${editingExamId}`:'/admin/exams';const method=editingExamId?'PUT':'POST';const{ok,data}=await apiFetch(url,{method,body:JSON.stringify(body)});if(ok){closeModal('examModal');toast('Exam saved');await loadExams();await loadDashboard()}else alert(data.error||'Failed to save exam')}
async function deleteExam(id){if(confirm('Delete this exam?')){await apiFetch(`/admin/exams/${id}`,{method:'DELETE'});toast('Exam deleted');await loadExams();await loadDashboard()}}
async function toggleExam(id){const e=allExams.find(x=>x.id==id);if(!e)return;await apiFetch(`/admin/exams/${id}/toggle`,{method:'POST',body:JSON.stringify({is_closed:e.is_closed?0:1})});toast('Exam '+(e.is_closed?'opened':'closed'));await loadExams()}

function copyBatchLink(){const inp=document.getElementById('batchSlugDisplay');inp.select();navigator.clipboard?.writeText(inp.value).then(()=>toast('Link copied')).catch(()=>document.execCommand('copy'))}

// --- Batch Access Codes ---
function currentBatchCodesId(){return document.getElementById('batchCodesSelect').value||null}
async function loadBatchCodes(){const id=currentBatchCodesId();if(!id)return;const{data}=await apiFetch(`/admin/batches/${id}/codes`);renderBatchCodes(data||[])}
function renderBatchCodes(codes){document.getElementById('batchCodesTable').innerHTML=`<table><thead><tr><th>Code</th><th>Status</th><th>Used By</th><th>Created</th><th>Used</th><th></th></tr></thead><tbody>${codes.map(c=>`<tr><td style="font-family:monospace">${esc(c.code)}</td><td>${c.status==='used'?'<span class="badge badge-closed">Used</span>':'<span class="badge badge-open">Active</span>'}</td><td>${c.used_by_name?`${esc(c.used_by_name)}<br><span style="font-size:.65rem;color:var(--t4)">${esc(c.used_by_email)}</span>`:'—'}</td><td>${formatDate(c.created_at)}</td><td>${c.used_at?formatDate(c.used_at):'—'}</td><td><button class="btn btn-danger btn-sm" onclick="deleteBatchCode(${c.id})">Delete</button></td></tr>`).join('')||'<tr><td colspan="6" style="text-align:center;padding:24px;color:var(--t3)">No codes generated yet</td></tr>'}</tbody></table>`}
async function generateBatchCode(){const id=currentBatchCodesId();if(!id)return;const{ok,data}=await apiFetch(`/admin/batches/${id}/codes`,{method:'POST'});if(ok){document.getElementById('newCodeBanner').innerHTML=`<div class="alert alert-success" style="font-family:monospace;font-size:1rem;font-weight:600;display:flex;align-items:center;justify-content:space-between;gap:12px">${esc(data.code)}<button class="btn btn-outline btn-sm" onclick="copyText('${data.code}')">Copy</button></div>`;toast('Code generated');await loadBatchCodes()}else alert(data.error||'Failed to generate code')}
function copyText(t){navigator.clipboard?.writeText(t).then(()=>toast('Copied')).catch(()=>{})}
async function deleteBatchCode(codeId){if(!confirm('Delete this code?\n\nIf it has already been used, the student keeps their access — this only removes the code record.'))return;const{ok,data}=await apiFetch(`/admin/batch-codes/${codeId}`,{method:'DELETE'});if(ok){toast('Code deleted');await loadBatchCodes()}else alert(data.error||'Failed to delete code')}
async function clearUsedBatchCodes(){const id=currentBatchCodesId();if(!id)return;if(!confirm('Clear all used codes for this batch?\n\nThis only deletes the code history to save space — everyone who already redeemed a code keeps their access. This cannot be undone.'))return;const{ok,data}=await apiFetch(`/admin/batches/${id}/codes-used`,{method:'DELETE'});if(ok){toast('Used codes cleared');await loadBatchCodes()}else alert(data.error||'Failed to clear codes')}

function openBatchModal(id=null){editingBatchId=id;const b=id?allBatches.find(x=>x.id==id):null;document.getElementById('batchModalTitle').textContent=id?'Edit Batch':'New Batch';document.getElementById('batchName').value=b?.name||'';document.getElementById('batchDesc').value=b?.description||'';document.getElementById('batchImageUrl').value=b?.image_url||'';document.getElementById('batchFee').value=b?.fee||'';document.getElementById('batchIsPublic').checked=b?.is_public===1;const slugWrap=document.getElementById('batchSlugWrap');if(b?.public_slug){slugWrap.style.display='block';document.getElementById('batchSlugDisplay').value=window.location.origin+'/payment.html?batch='+b.public_slug}else{slugWrap.style.display='none'}document.getElementById('batchModal').classList.add('open')}
let currentBatchUsersId=null,currentBatchUsersName='';
function daysRemainingLabel(d){if(d===null||d===undefined)return'Permanent';if(d<=0)return'Expires today';return d+' day'+(d===1?'':'s')+' left'}
function batchUserRow(u,removeFn,tagCls,tagLabel){return `<div class="batch-user-row"><div class="batch-user-info"><div class="batch-user-name">${esc(u.name)} <span class="premium-tag ${tagCls}" style="margin-left:4px">${tagLabel}</span></div><div class="batch-user-email">${esc(u.email)}</div><div class="batch-user-days">${daysRemainingLabel(u.days_remaining)}</div></div><button class="btn btn-danger btn-xs" onclick="${removeFn}">Remove</button></div>`}
async function openBatchUsersModal(id,name){currentBatchUsersId=id;currentBatchUsersName=name;document.getElementById('batchUsersTitle').textContent='Users — '+name;document.getElementById('batchUsersBody').innerHTML='<div class="skeleton" style="height:40px"></div>';document.getElementById('batchUsersModal').classList.add('open');await loadBatchUsers()}
async function loadBatchUsers(){const{ok,data}=await apiFetch(`/admin/batches/${currentBatchUsersId}/users`);if(!ok){document.getElementById('batchUsersBody').innerHTML='<p style="color:var(--t3);text-align:center;padding:16px">Failed to load.</p>';return}const bu=data.batch_users||[],au=data.account_users||[];let html='';html+=`<div class="batch-users-group-label">Batch Premium (${bu.length})</div>`;html+=bu.length?bu.map(u=>batchUserRow(u,`removeBatchUser(${u.user_id})`,'pt-batch','Batch')).join(''):'<p style="color:var(--t4);font-size:.75rem;padding:6px 0">No one has been granted premium for this batch specifically.</p>';html+=`<div class="batch-users-group-label">Account-wide Premium (${au.length})</div>`;html+=au.length?au.map(u=>batchUserRow(u,`removeAccountUser(${u.user_id})`,'pt-account','Account')).join(''):'<p style="color:var(--t4);font-size:.75rem;padding:6px 0">No account-wide premium users.</p>';document.getElementById('batchUsersBody').innerHTML=html}
async function removeBatchUser(uid){if(!confirm('Remove this user\'s access to this batch?'))return;await apiFetch('/admin/revoke-premium',{method:'DELETE',body:JSON.stringify({user_id:uid,batch_id:currentBatchUsersId})});toast('Removed from batch');await loadBatchUsers();await loadUsers()}
async function removeAccountUser(uid){if(!confirm('This user has account-wide premium, which gives them access to every batch and exam — not just this one. Revoke it entirely?'))return;await apiFetch('/admin/revoke-account-premium',{method:'DELETE',body:JSON.stringify({user_id:uid})});toast('Account premium revoked');await loadBatchUsers();await loadUsers()}
async function saveBatch(){const body={name:document.getElementById('batchName').value.trim(),description:document.getElementById('batchDesc').value,image_url:document.getElementById('batchImageUrl').value.trim(),fee:parseFloat(document.getElementById('batchFee').value)||0,is_public:document.getElementById('batchIsPublic').checked?1:0};const url=editingBatchId?`/admin/batches/${editingBatchId}`:'/admin/batches';const method=editingBatchId?'PUT':'POST';const{ok,data}=await apiFetch(url,{method,body:JSON.stringify(body)});if(ok){await loadBatches();await loadExams();await loadDashboard();if(!editingBatchId&&data?.public_slug){editingBatchId=data.id;document.getElementById('batchModalTitle').textContent='Edit Batch';document.getElementById('batchSlugWrap').style.display='block';document.getElementById('batchSlugDisplay').value=window.location.origin+'/payment.html?batch='+data.public_slug;toast('Batch created — copy its payment link below')}else{closeModal('batchModal');toast('Batch saved')}}}
async function deleteBatch(id){if(confirm('Delete this batch?')){await apiFetch(`/admin/batches/${id}`,{method:'DELETE'});toast('Batch deleted');await loadBatches();await loadExams();await loadDashboard()}}

async function loadQuestionsForExam(){const id=document.getElementById('questionExamSelect').value;if(!id){document.getElementById('questionsList').innerHTML='<p style="color:var(--t3);padding:16px">Select an exam</p>';return}const{data}=await apiFetch(`/admin/questions/${id}`);const qs=data||[];document.getElementById('questionsList').innerHTML=qs.length?qs.map((q,i)=>`<div style="padding:10px;border-bottom:1px solid var(--border)"><strong>${i+1}.</strong> ${q.section?`<span style="background:#e8f0fe;color:var(--blue);font-size:.65rem;padding:2px 8px;border-radius:20px;margin-right:6px">${esc(q.section)}</span>`:''}${esc(q.question_text||'')} <span style="color:var(--green)">(${q.correct_answer})</span></div>`).join(''):'<p style="color:var(--t3);padding:20px;text-align:center">No questions yet</p>'}
async function uploadQuestions(){const examId=document.getElementById('questionExamSelect').value;const json=document.getElementById('questionsJson').value;const section=document.getElementById('uploadSectionSelect').value;if(!examId||!json){alert('Select exam and paste JSON');return}try{const questions=JSON.parse(json);if(document.getElementById('replaceQuestions').checked)await apiFetch(`/admin/questions/${examId}`,{method:'DELETE'});const{data}=await apiFetch('/admin/questions/bulk',{method:'POST',body:JSON.stringify({exam_id:parseInt(examId),questions,section})});document.getElementById('questionUploadResult').innerHTML=`<div class="alert alert-success">${data.inserted} questions uploaded</div>`;setTimeout(()=>document.getElementById('questionUploadResult').innerHTML='',3000);clearQuestionsJson();await loadQuestionsForExam();await loadExams();await loadDashboard()}catch(e){alert('Invalid JSON format')}}
async function deleteAllQuestions(){const id=document.getElementById('questionExamSelect').value;if(id&&confirm('Delete ALL questions?')){await apiFetch(`/admin/questions/${id}`,{method:'DELETE'});await loadQuestionsForExam();await loadExams();await loadDashboard()}}

function setResourceType(t){currentResourceType=t;document.querySelectorAll('.resource-type-btn').forEach(b=>b.classList.toggle('active',b.dataset.type===t));document.getElementById('resourceExamGroup').style.display=t==='exam'?'block':'none';document.getElementById('resourceBatchGroup').style.display=t==='batch'?'block':'none';loadResourcesForTarget()}
async function loadResourcesForTarget(){const id=currentResourceType==='exam'?document.getElementById('resourceExamSelect').value:document.getElementById('resourceBatchSelect').value;if(!id){document.getElementById('resourcesList').innerHTML='<div class="resource-empty">Select an exam or batch</div>';return}currentResourceTargetId=parseInt(id);const ep=currentResourceType==='exam'?`/admin/exams/${id}/resources`:`/admin/batches/${id}/resources`;const{data}=await apiFetch(ep);const rs=data||[];document.getElementById('resourcesList').innerHTML=rs.length?`<div class="resource-list">${rs.map(r=>`<div class="resource-item"><div class="resource-info"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20"/><path d="M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2z"/></svg><div><div class="resource-title">${esc(r.title)}</div><div class="resource-link">${isImageURL(r.link)?`<img src="${esc(r.link)}" class="resource-link-img" alt="">`:esc(r.link)}</div></div></div><div class="resource-actions"><button class="btn btn-danger btn-sm" onclick="deleteResource(${r.id})">Delete</button></div></div>`).join('')}</div>`:'<div class="resource-empty">No resources added yet</div>'}
async function addResource(){const t=document.getElementById('newResourceTitle').value.trim();const l=document.getElementById('newResourceLink').value.trim();if(!currentResourceTargetId||!t||!l){alert('Select target and fill all fields');return}const ep=currentResourceType==='exam'?'/admin/resources':'/admin/batch-resources';const body=currentResourceType==='exam'?{exam_id:currentResourceTargetId,title:t,link:l}:{batch_id:currentResourceTargetId,title:t,link:l};const{ok}=await apiFetch(ep,{method:'POST',body:JSON.stringify(body)});if(ok){document.getElementById('newResourceTitle').value='';document.getElementById('newResourceLink').value='';toast('Resource added');await loadResourcesForTarget()}}
async function deleteResource(id){if(confirm('Delete this resource?')){const ep=currentResourceType==='exam'?`/admin/resources/${id}`:`/admin/batch-resources/${id}`;await apiFetch(ep,{method:'DELETE'});toast('Resource deleted');await loadResourcesForTarget()}}

let userFilterType='all';
function userRowHtml(u){let prem='';if(u.premium_grants&&u.premium_grants.length){prem=u.premium_grants.map(g=>{const c=g.grant_scope==='exam'?'pt-exam':g.grant_scope==='batch'?'pt-batch':'pt-account';const n=g.exam_name||g.batch_name||(g.grant_scope==='account'?'Account':g.grant_scope);const rf=g.grant_scope==='exam'?`revokeExamPremium(${u.id},${g.exam_id})`:g.grant_scope==='batch'?`revokeBatchPremium(${u.id},${g.batch_id})`:`revokeAccountPremium(${u.id})`;return `<span class="premium-tag ${c}">${esc(n)}<button class="revoke-btn" onclick="${rf}">✕</button></span>`}).join('')}else prem='<span style="color:var(--t4);font-size:.7rem">None</span>';let st='<span class="badge badge-free">Active</span>';if(u.is_banned)st='<span class="badge badge-banned">Banned</span>';else if(u.is_admin)st='<span class="badge badge-admin">Admin</span>';let act='';if(!u.is_admin){act=`<button class="btn btn-primary btn-xs" onclick="openGrantModal(${u.id},'${esc(u.name)}')">Grant</button>`;if(u.is_banned)act+=` <button class="btn btn-outline btn-xs" onclick="unbanUser(${u.id})">Unban</button>`;else act+=` <button class="btn btn-outline btn-xs" style="color:#e37400;border-color:#e37400" onclick="confirmBan(${u.id},'${esc(u.name)}')">Ban</button>`;act+=` <button class="btn btn-danger btn-xs" onclick="confirmDeleteUser(${u.id},'${esc(u.name)}')">Delete</button>`}return `<tr><td><strong>${esc(u.name)}</strong></td><td style="color:var(--t4);font-size:.75rem">${esc(u.email)}</td><td>${u.is_admin?'Admin':'Student'}</td><td>${st}</td><td style="max-width:180px">${prem}</td><td>${act||'—'}</td></tr>`}
function isActiveGrant(g){return!g.expires_at||new Date(g.expires_at).getTime()>Date.now()}
function userMatchesPremiumFilter(u){
  if(userFilterType==='all')return true;
  const grants=u.premium_grants||[];
  const now=Date.now();
  if(userFilterType==='batch'){
    const bg=grants.filter(g=>g.grant_scope==='batch'&&isActiveGrant(g));
    if(!bg.length)return false;
    const bid=document.getElementById('userFilterBatchId').value;
    return bid?bg.some(g=>String(g.batch_id)===String(bid)):true;
  }
  if(userFilterType==='exam'){
    const eg=grants.filter(g=>g.grant_scope==='exam'&&isActiveGrant(g));
    if(!eg.length)return false;
    const eid=document.getElementById('userFilterExamId').value;
    return eid?eg.some(g=>String(g.exam_id)===String(eid)):true;
  }
  if(userFilterType==='account')return!!(u.premium_until&&new Date(u.premium_until).getTime()>now);
  if(userFilterType==='none'){
    const hasBatch=grants.some(g=>g.grant_scope==='batch'&&isActiveGrant(g));
    const hasExam=grants.some(g=>g.grant_scope==='exam'&&isActiveGrant(g));
    const hasAccount=!!(u.premium_until&&new Date(u.premium_until).getTime()>now);
    return!hasBatch&&!hasExam&&!hasAccount;
  }
  return true;
}
function onUserFilterTypeChange(){
  userFilterType=document.getElementById('userFilterType').value;
  usersPageNum=1;
  document.getElementById('userFilterBatchWrap').style.display=userFilterType==='batch'?'block':'none';
  document.getElementById('userFilterExamWrap').style.display=userFilterType==='exam'?'block':'none';
  if(userFilterType==='batch'){document.getElementById('userFilterBatchId').value='';registerSearchableSelect('userFilterBatchWrap',[{value:'',label:'Any batch',desc:''}].concat(allBatches.map(b=>({value:b.id,label:b.name,desc:(b.exam_count||0)+' exams'}))),'userFilterBatchId',()=>renderUsersTable(),{defaultValue:'',placeholder:'Any batch'});updateSearchableSelectUI('userFilterBatchWrap')}
  if(userFilterType==='exam'){document.getElementById('userFilterExamId').value='';registerSearchableSelect('userFilterExamWrap',[{value:'',label:'Any exam',desc:''}].concat(allExams.map(e=>({value:e.id,label:e.name,desc:e.batch_name||''}))),'userFilterExamId',()=>renderUsersTable(),{defaultValue:'',placeholder:'Any exam'});updateSearchableSelectUI('userFilterExamWrap')}
  renderUsersTable();
}
function renderUsersTable(){const filteredAll=allUsers.filter(userMatchesPremiumFilter);const{items:filtered,page,totalPages,total}=paginateList(filteredAll,usersPageNum,PAGE_SIZE);usersPageNum=page;document.getElementById('usersTable').innerHTML=`<table><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Status</th><th>Premium</th><th>Actions</th></tr></thead><tbody>${filtered.map(userRowHtml).join('')||'<tr><td colspan="6" style="text-align:center;padding:24px;color:var(--t3)">No users match this filter</td></tr>'}</tbody></table>${pagerHtml(page,totalPages,total,'goToUsersPage')}`;const activeQuery=document.getElementById('userSearchInput')?.value;if(activeQuery)onUserSearchInput()}
function goToUsersPage(p){usersPageNum=p;renderUsersTable()}
async function loadUsers(){const{data}=await apiFetch('/admin/users');allUsers=Array.isArray(data)?data:[];renderUsersTable()}

function openGrantModal(id,name){grantUserId=id;document.getElementById('grantUserDisplay').textContent=name;registerSearchableSelect('grantExamSelectWrap',allExams.map(e=>({value:e.id,label:e.name,desc:e.batch_name||''})),'grantExam',()=>{},{defaultValue:'',placeholder:'Search exams...'});registerSearchableSelect('grantBatchSelectWrap',allBatches.map(b=>({value:b.id,label:b.name,desc:(b.exam_count||0)+' exams'})),'grantBatch',()=>{},{defaultValue:'',placeholder:'Search batches...'});updateSearchableSelectUI('grantExamSelectWrap');updateSearchableSelectUI('grantBatchSelectWrap');toggleGrantScope();document.getElementById('grantModal').classList.add('open')}
function toggleGrantScope(){const s=document.getElementById('grantScope').value;document.getElementById('grantExamGroup').style.display=s==='exam'?'block':'none';document.getElementById('grantBatchGroup').style.display=s==='batch'?'block':'none'}
async function submitGrant(){const s=document.getElementById('grantScope').value;const d=document.getElementById('grantDuration').value;const body={user_id:grantUserId,grant_scope:s,duration_hours:d?parseInt(d):null};if(s==='exam')body.exam_id=parseInt(document.getElementById('grantExam').value);if(s==='batch')body.batch_id=parseInt(document.getElementById('grantBatch').value);const{ok}=await apiFetch('/admin/grant-premium',{method:'POST',body:JSON.stringify(body)});if(ok){closeModal('grantModal');toast('Premium granted');await loadUsers()}}
async function revokeExamPremium(uid,eid){if(!confirm('Revoke exam premium?'))return;await apiFetch('/admin/revoke-premium',{method:'DELETE',body:JSON.stringify({user_id:uid,exam_id:eid})});toast('Premium revoked');await loadUsers()}
async function revokeBatchPremium(uid,bid){if(!confirm('Revoke batch premium?'))return;await apiFetch('/admin/revoke-premium',{method:'DELETE',body:JSON.stringify({user_id:uid,batch_id:bid})});toast('Premium revoked');await loadUsers()}
async function revokeAccountPremium(uid){if(!confirm('Revoke account premium?'))return;await apiFetch('/admin/revoke-account-premium',{method:'DELETE',body:JSON.stringify({user_id:uid})});toast('Premium revoked');await loadUsers()}

function confirmBan(uid,name){document.getElementById('confirmActionTitle').textContent='Ban User';document.getElementById('confirmActionBody').innerHTML=`<p>Are you sure you want to <strong style="color:#e37400">ban</strong> <strong>${esc(name)}</strong>?</p><p style="font-size:.8rem;color:var(--t3)">They will be unable to login. Data preserved.</p>`;document.getElementById('confirmActionFooter').innerHTML=`<button class="btn btn-outline" onclick="closeModal('confirmActionModal')">Cancel</button><button class="btn btn-primary" style="background:#e37400" onclick="banUser(${uid})">Ban User</button>`;document.getElementById('confirmActionModal').classList.add('open')}
function confirmDeleteUser(uid,name){document.getElementById('confirmActionTitle').textContent='Delete User Permanently';document.getElementById('confirmActionBody').innerHTML=`<p style="color:var(--red);font-weight:500">This action CANNOT be undone.</p><p>This will permanently delete <strong>${esc(name)}</strong> and all related accounts.</p>`;document.getElementById('confirmActionFooter').innerHTML=`<button class="btn btn-outline" onclick="closeModal('confirmActionModal')">Cancel</button><button class="btn btn-danger" onclick="deleteUser(${uid})">Delete Permanently</button>`;document.getElementById('confirmActionModal').classList.add('open')}
async function banUser(id){const{ok}=await apiFetch(`/admin/users/${id}/ban`,{method:'POST'});if(ok){closeModal('confirmActionModal');toast('User banned');await loadUsers()}}
async function unbanUser(id){const{ok}=await apiFetch(`/admin/users/${id}/unban`,{method:'POST'});if(ok){toast('User unbanned');await loadUsers()}}
async function deleteUser(id){const{ok}=await apiFetch(`/admin/users/${id}/delete`,{method:'DELETE'});if(ok){closeModal('confirmActionModal');toast('User deleted');await loadUsers();await loadDashboard()}}

function onUserSearchInput(){const val=document.getElementById('userSearchInput').value;const btn=document.getElementById('userSearchClear');const box=document.getElementById('userSearchResults');btn.style.display=val?'flex':'none';if(!normalizeSearch(val)){box.classList.remove('show');box.innerHTML='';return}const matches=fuzzyUserSearch(val);if(!matches.length){box.innerHTML='<div class="user-search-empty">No matching users found</div>';box.classList.add('show');return}box.innerHTML=matches.map(u=>{let st='';if(u.is_banned)st='<span class="badge badge-banned">Banned</span>';else if(u.is_admin)st='<span class="badge badge-admin">Admin</span>';let actions=`<button class="btn btn-primary btn-xs" onclick="event.stopPropagation();openGrantModal(${u.id},'${esc(u.name)}')">Grant</button>`;if(!u.is_admin){if(u.is_banned)actions+=` <button class="btn btn-outline btn-xs" onclick="event.stopPropagation();unbanUser(${u.id})">Unban</button>`;else actions+=` <button class="btn btn-outline btn-xs" style="color:#e37400" onclick="event.stopPropagation();confirmBan(${u.id},'${esc(u.name)}')">Ban</button>`;actions+=` <button class="btn btn-danger btn-xs" onclick="event.stopPropagation();confirmDeleteUser(${u.id},'${esc(u.name)}')">Delete</button>`}return `<div class="user-search-item"><div class="user-search-main" onclick="openGrantModal(${u.id},'${esc(u.name)}')"><div class="user-search-name">${esc(u.name)} ${st}</div><div class="user-search-email">${esc(u.email)}</div></div><div class="user-search-actions">${actions}</div></div>`}).join('');box.classList.add('show')}
function clearUserSearch(){document.getElementById('userSearchInput').value='';document.getElementById('userSearchClear').style.display='none';document.getElementById('userSearchResults').classList.remove('show');document.getElementById('userSearchResults').innerHTML=''}

async function loadResults(){const id=document.getElementById('resultFilterExam').value;const url=id?`/admin/results/${id}`:'/admin/results';const{data}=await apiFetch(url);const rsAll=Array.isArray(data)?data:[];let toolbar='';if(id){const exam=allExams.find(e=>e.id==id);toolbar=`<button class="btn btn-primary btn-sm" onclick="downloadResults(${id})">Download TXT</button> <button class="btn btn-danger btn-sm" onclick="deleteExamResults(${id},'${esc(exam?exam.name:'').replace(/'/g,"\\'")}')">Delete All Results (This Exam)</button>`}else if(rsAll.length){toolbar=`<button class="btn btn-danger btn-sm" onclick="deleteAllResultsEverywhere()">Delete ALL Results (Every Exam)</button>`}const{items:rs,page,totalPages,total}=paginateList(rsAll,resultsPageNum,PAGE_SIZE);resultsPageNum=page;document.getElementById('resultsTable').innerHTML=`<div style="margin-bottom:8px">${toolbar}</div><table><thead><tr><th>Rank</th><th>User</th><th>Exam</th><th>Score</th><th>%</th><th>Time</th><th>Date</th><th></th></tr></thead><tbody>${rs.map(r=>`<tr><td><strong>#${r.rank||'—'}</strong></td><td><strong>${esc(r.user_name)}</strong><br><span style="font-size:.65rem;color:var(--t4)">${esc(r.user_email)}</span></td><td>${esc(r.exam_name)}</td><td>${r.score}/${r.total_questions}</td><td><span style="color:${(r.percentage||0)>=80?'var(--green)':(r.percentage||0)>=50?'#e37400':'var(--red)'}">${(r.percentage||0).toFixed(1)}%</span></td><td>${formatTimeTaken(r.time_taken_seconds)}</td><td>${formatDate(r.submitted_at)}</td><td><button class="btn btn-danger btn-sm" onclick="deleteResult(${r.id},'${esc(r.user_name).replace(/'/g,"\\'")}','${esc(r.exam_name).replace(/'/g,"\\'")}')">Delete</button></td></tr>`).join('')||'<tr><td colspan="8">No results</td></tr>'}</tbody></table>${pagerHtml(page,totalPages,total,'goToResultsPage')}`}
function goToResultsPage(p){resultsPageNum=p;loadResults()}
function downloadResults(id){const t=getToken();fetch(API+'/admin/results/'+id+'/download',{headers:{'Authorization':'Bearer '+t}}).then(r=>r.blob()).then(b=>{const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='results.txt';a.click()})}
async function deleteResult(resultId,userName,examName){if(!confirm(`Delete ${userName}'s result for "${examName}"?\n\nThis permanently removes this result from the backend. This cannot be undone.`))return;const{ok,data}=await apiFetch(`/admin/results/${resultId}`,{method:'DELETE'});if(ok){toast('Result deleted');await loadResults();await loadDashboard()}else alert(data.error||'Failed to delete result')}
async function deleteExamResults(examId,examName){if(!confirm(`Delete ALL results for "${examName||'this exam'}"?\n\nEvery user's result for this exam will be permanently removed from the backend and the leaderboard will be cleared. This cannot be undone.`))return;const{ok,data}=await apiFetch(`/admin/exams/${examId}/results`,{method:'DELETE'});if(ok){toast('All results for this exam deleted');await loadResults();await loadDashboard()}else alert(data.error||'Failed to delete results')}
async function deleteAllResultsEverywhere(){if(!confirm('Delete ALL results for EVERY exam on the platform?\n\nThis permanently removes every stored result and leaderboard entry across all exams from the backend. This cannot be undone.'))return;if(!confirm('Are you absolutely sure? This affects every exam and cannot be reversed.'))return;const{ok,data}=await apiFetch('/admin/results',{method:'DELETE'});if(ok){toast('All results deleted');await loadResults();await loadDashboard()}else alert(data.error||'Failed to delete results')}

function toggleNotifTarget(){const s=document.getElementById('notifTarget').value;document.getElementById('notifBatchGroup').style.display=s==='batch'?'block':'none';if(s==='batch'){registerSearchableSelect('notifBatchSelectWrap',allBatches.map(b=>({value:b.id,label:b.name,desc:(b.exam_count||0)+' exams'})),'notifBatchId',()=>{},{defaultValue:'',placeholder:'Search batches...'});updateSearchableSelectUI('notifBatchSelectWrap')}}
async function sendNotification(){const title=document.getElementById('notifTitle').value.trim();if(!title){alert('Title required');return}const targetType=document.getElementById('notifTarget').value;const targetBatchId=document.getElementById('notifBatchId').value;if(targetType==='batch'&&!targetBatchId){alert('Select a batch to notify');return}const body={title,body:document.getElementById('notifBody').value,image_url:document.getElementById('notifImage').value||null,link_url:document.getElementById('notifLink').value||null,target_type:targetType,target_batch_id:targetType==='batch'?parseInt(targetBatchId):null};const{ok}=await apiFetch('/admin/notifications',{method:'POST',body:JSON.stringify(body)});if(ok){document.getElementById('notifResult').innerHTML='<div class="alert alert-success">Notification sent!</div>';document.getElementById('notifTitle').value='';document.getElementById('notifBody').value='';document.getElementById('notifImage').value='';document.getElementById('notifLink').value='';document.getElementById('notifTarget').value='all';document.getElementById('notifBatchId').value='';toggleNotifTarget();toast('Notification sent');await loadNotificationsList();setTimeout(()=>document.getElementById('notifResult').innerHTML='',3000)}}
async function loadNotificationsList(){const{data}=await apiFetch('/admin/notifications');const nsAll=data||[];const{items:ns,page,totalPages,total}=paginateList(nsAll,notifPageNum,8);notifPageNum=page;document.getElementById('notifList').innerHTML=(ns.length?ns.map(n=>{const targetBadge=n.target_type==='batch'?`<span class="badge badge-sectional" style="background:#e0e7ff;color:#4338ca">Batch: ${esc(n.target_batch_name||'Unknown')}</span>`:'<span class="badge badge-free">Everyone</span>';return `<div class="notif-card"><div class="notif-header"><div class="notif-title">${esc(n.title)}</div><button class="btn btn-danger btn-sm" onclick="deleteNotification(${n.id})">Delete</button></div><div class="notif-meta">${targetBadge}<span><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg>${formatDate(n.created_at)}</span><span><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"/><circle cx="12" cy="12" r="3"/></svg>${n.read_count||0}/${n.total_users||0} read</span><span style="color:var(--t4);font-size:.65rem">by ${esc(n.creator_name||'')}</span></div>${n.body?`<div class="notif-body">${esc(n.body)}</div>`:''}${n.image_url?`<img src="${esc(n.image_url)}" class="notif-img" onerror="this.style.display='none'">`:''}${n.link_url?`<a href="${esc(n.link_url)}" target="_blank" class="notif-link">Open Link</a>`:''}</div>`}).join(''):'<p style="color:var(--t3);text-align:center;padding:16px">No notifications sent</p>')+pagerHtml(page,totalPages,total,'goToNotifPage')}
function goToNotifPage(p){notifPageNum=p;loadNotificationsList()}
async function deleteNotification(id){if(confirm('Delete this notification?')){await apiFetch(`/admin/notifications/${id}`,{method:'DELETE'});toast('Notification deleted');await loadNotificationsList()}}

function toggleMobileNav(){document.getElementById('mobileNavDropdown').classList.toggle('show')}
document.addEventListener('click',e=>{const dd=document.getElementById('mobileNavDropdown');const hb=document.getElementById('hamburger');if(dd&&!dd.contains(e.target)&&!hb.contains(e.target))dd.classList.remove('show')})
function switchSection(s){document.querySelectorAll('.section').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.sidebar-item').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.mobile-nav-dropdown .sidebar-item').forEach(x=>x.classList.remove('active'));document.getElementById('sec-'+s).classList.add('active');document.querySelector(`.sidebar-item[onclick="switchSection('${s}')"]`)?.classList.add('active');document.querySelector(`.mobile-nav-dropdown .sidebar-item[onclick="switchSection('${s}')"]`)?.classList.add('active');if(s==='dashboard')loadDashboard();if(s==='exams')loadExams();if(s==='batches')loadBatches();if(s==='questions'){loadQuestionsForExam()}if(s==='resources'){rebuildSearchableSelects()}if(s==='users')loadUsers();if(s==='results'){rebuildSearchableSelects();loadResults()}if(s==='notifications')loadNotificationsList();document.getElementById('mobileNavDropdown').classList.remove('show')}
function openModal(id){document.getElementById(id).classList.add('open')}
function closeModal(id){document.getElementById(id).classList.remove('open')}
document.querySelectorAll('.modal-overlay').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)m.classList.remove('open')}))
document.addEventListener('keydown',e=>{if(e.key==='Escape')document.querySelectorAll('.modal-overlay.open').forEach(m=>m.classList.remove('open'))})

loadDashboard();loadExams();loadBatches();loadUsers();loadNotificationsList();
