name = "mcq-exam-system"
compatibility_date = "2024-01-01"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "exalyte"
database_id = "db85dc30-953a-4337-9a26-2e1db522117e"
